
local hl = vim.api.nvim_set_hl
hl(0, 'CursorLineNr', { fg = '#ffa200' })
hl(0, 'LineNr', { fg = '#ffffff' })

hl(0, '@function.call.c', { fg = '#00a2ff' })
hl(0, '@type.builtin.c', { fg = '#dd00ff' })
hl(0, '@keyword.modifier.c', { fg = '#cf03fc' })
hl(0, '@keyword.import.c', { fg = '#fcc603' })
hl(0, '@variable.parameter.c', { fg = '#dbb8ff' })
hl(0, '@character.printf', { fg = '#ff3700' })
hl(0, '@number.c', { fg = '#00f2ff' })
hl(0, '@constant.c', { fg = '#00f2ff' })
hl(0, '@constant.macro.c', { fg = '#d67dff' })
hl(0, '@variable.c', { fg = '#dfc4ff' })
hl(0, '@keyword.repeat.c', { fg = '#f00019' })
hl(0, '@keyword.conditional.c', { fg = '#ff0019' })
hl(0, '@keyword.return.c', { fg = '#ff0019' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
-- hl(0, '', { fg = '' })
